import React from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { trackEvent } from '../lib/telemetry'

const differentiators = [
  {
    title: 'White-label experiences',
    body: 'Launch a brokerage-branded portal with custom domains, colors, typography, and localized content per territory.',
  },
  {
    title: 'Operational command center',
    body: 'Unify both residential and commercial inventory with pipeline tracking, marketing workflows, and compliance tooling.',
  },
  {
    title: 'Data-rich storytelling',
    body: 'Transform raw listings into curated landing pages, analytics dashboards, and investor-ready reports in a few clicks.',
  },
]

const platformPillars = [
  {
    title: 'Inventory & Projects',
    bullets: [
      'Unified database covering pre-construction, sales, rentals, and exclusive mandates',
      'Bulk import via spreadsheets or direct Supabase/Prisma connections',
      'Media management with video, drone, and floor plan support',
    ],
  },
  {
    title: 'Deal Room & CRM',
    bullets: [
      'Pipeline stages tailored for acquisitions, co-brokerage, and buyer journeys',
      'Secure document vault with watermarking and permission tiers',
      'Activity timelines, reminders, and handoff automation between agents',
    ],
  },
  {
    title: 'Marketing Engine',
    bullets: [
      'Autogenerated property brochures, social media packs, and email campaigns',
      'Localized landing pages with embedded calendaring and WhatsApp follow-up',
      'A/B content testing and performance scoring for every listing or project',
    ],
  },
  {
    title: 'Operations & Compliance',
    bullets: [
      'Team onboarding wizard with role-based access and equipment checklists',
      'Document compliance dashboards with expiration alerts',
      'Audit-ready history of site settings, policy updates, and approvals',
    ],
  },
]

const services = [
  {
    title: 'Implementation',
    points: [
      'Research & discovery workshops with brokerage stakeholders',
      'Data migration and environment setup (dev/staging/production)',
      'Training playbooks for agents, admins, and marketing teams',
    ],
  },
  {
    title: 'Customization',
    points: [
      'Tailored modules for franchise networks or boutique teams',
      'Custom integrations (ERPs, marketing suites, BI tools)',
      'Dedicated design systems for consistent brand rollouts',
    ],
  },
  {
    title: 'Ongoing Success',
    points: [
      'Roadmap co-planning with your leadership team each quarter',
      '24/7 monitoring, SLA-based support, and feature request queueing',
      'Analytics reviews to surface revenue opportunities and gaps',
    ],
  },
]

export default function Institutional() {
  const { t } = useTranslation()
  const handleHeroCta = React.useCallback(() => {
    trackEvent('signup_cta_click', { position: 'institucional' })
  }, [])
  return (
    <div className="bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-100">
      <section className="bg-gradient-to-br from-brand-600 via-brand-500 to-brand-700 text-white">
        <div className="container-padded py-20 lg:py-24">
          <p className="uppercase tracking-[0.4em] text-xs font-semibold text-white/80">Brokerage Platform</p>
          <h1 className="mt-4 text-3xl sm:text-4xl lg:text-5xl font-semibold leading-tight">
            {t('pages.institutional.title')} Platform for Ambitious Real Estate Teams
          </h1>
          <p className="mt-6 max-w-2xl text-lg sm:text-xl text-white/90">
            Stella powers customizable, enterprise-grade experiences for brokers who want more than a listings website.
            Combine marketing firepower, agent productivity, and investor-ready reporting in one cohesive platform.
          </p>
          <div className="mt-8 flex flex-col sm:flex-row gap-3">
            <Link
              to="/criar-site"
              onClick={handleHeroCta}
              className="inline-flex items-center justify-center gap-2 rounded-full bg-white text-brand-700 px-6 py-3 text-sm font-semibold shadow-lg shadow-brand-800/20 hover:bg-slate-100 transition"
            >
              Criar meu site
            </Link>
            <Link
              to="/contato"
              className="inline-flex items-center justify-center gap-2 rounded-full border border-white/40 px-6 py-3 text-sm font-semibold hover:bg-white/10 transition"
            >
              Schedule a discovery call
            </Link>
            <a
              href="#capabilities"
              className="inline-flex items-center justify-center gap-2 rounded-full border border-white/40 px-6 py-3 text-sm font-semibold hover:bg-white/10 transition"
            >
              Explore capabilities
            </a>
          </div>
        </div>
      </section>

      <section className="container-padded py-16 space-y-12">
        <div className="grid gap-6 lg:grid-cols-3">
          {differentiators.map((item) => (
            <div key={item.title} className="rounded-2xl border border-white/60 bg-white/70 dark:bg-slate-900/70 p-6 backdrop-blur shadow-sm">
              <h2 className="text-lg font-semibold text-brand-700 dark:text-brand-300">{item.title}</h2>
              <p className="mt-3 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{item.body}</p>
            </div>
          ))}
        </div>

        <div id="capabilities" className="space-y-6">
          <div className="flex flex-col gap-3">
            <p className="text-xs uppercase tracking-[0.3em] text-slate-400 dark:text-slate-500">Platform Pillars</p>
            <h2 className="text-2xl font-semibold">What your brokerage can operate on day one</h2>
            <p className="text-sm text-slate-600 dark:text-slate-300 max-w-3xl">
              The Stella admin you see today becomes a launch pad for franchise networks, boutique teams, and cross-border alliances.
              Every module is extensible, permission-aware, and instrumented for analytics.
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-2">
            {platformPillars.map((pillar) => (
              <div key={pillar.title} className="h-full rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 shadow-sm">
                <h3 className="text-xl font-semibold text-brand-700 dark:text-brand-400">{pillar.title}</h3>
                <ul className="mt-4 space-y-3 text-sm text-slate-600 dark:text-slate-300">
                  {pillar.bullets.map((bullet) => (
                    <li key={bullet} className="flex gap-3">
                      <span className="mt-1 h-2 w-2 rounded-full bg-brand-500 dark:bg-brand-400 flex-none" />
                      <span>{bullet}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>

        <div className="grid gap-6 lg:grid-cols-3">
          {services.map((service) => (
            <div key={service.title} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 shadow-sm">
              <p className="text-xs uppercase tracking-[0.3em] text-slate-400 dark:text-slate-500">{service.title}</p>
              <h3 className="mt-3 text-lg font-semibold text-slate-800 dark:text-slate-100">{service.title} partner care</h3>
              <ul className="mt-4 space-y-3 text-sm text-slate-600 dark:text-slate-300">
                {service.points.map((point) => (
                  <li key={point} className="flex gap-3">
                    <span className="mt-1 h-2 w-2 rounded-full bg-brand-500 dark:bg-brand-400 flex-none" />
                    <span>{point}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      <section className="bg-white dark:bg-slate-900 py-16">
        <div className="container-padded">
          <div className="rounded-3xl bg-gradient-to-r from-brand-600 via-brand-500 to-brand-700 px-8 py-12 text-white shadow-2xl">
            <h2 className="text-2xl font-semibold leading-tight">
              Ready to launch your next brokerage brand on Stella?
            </h2>
            <p className="mt-4 max-w-2xl text-sm text-white/90">
              We co-create your roadmap, integrate your tooling, and stand by with engineering and design resources that scale with your portfolio.
            </p>
            <div className="mt-6 flex flex-col sm:flex-row gap-3">
              <Link
                to="/contato"
                className="inline-flex items-center justify-center gap-2 rounded-full bg-white text-brand-700 px-6 py-3 text-sm font-semibold hover:bg-slate-100 transition"
              >
                Talk to our team
              </Link>
              <Link
                to="/admin"
                className="inline-flex items-center justify-center gap-2 rounded-full border border-white/50 px-6 py-3 text-sm font-semibold text-white hover:bg-white/10 transition"
              >
                Preview the admin suite
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
