// Ballet Store - State management and mock data for project management system

import { BalletState, Workspace, Project, Task, Goal, Portfolio, User } from './types'

// Mock data generator
const generateMockUsers = (): User[] => [
  { id: '1', name: 'Alice Johnson', email: 'alice@stella.com', role: 'admin', avatar: '👩‍💼' },
  { id: '2', name: 'Bob Smith', email: 'bob@stella.com', role: 'member', avatar: '👨‍💻' },
  { id: '3', name: 'Carol White', email: 'carol@stella.com', role: 'member', avatar: '👩‍🎨' },
  { id: '4', name: 'David Brown', email: 'david@stella.com', role: 'member', avatar: '👨‍🔧' },
]

const generateMockWorkspaces = (): Workspace[] => [
  {
    id: 'ws-1',
    name: 'Stella Real Estate',
    description: 'Main workspace for real estate operations',
    color: '#6366f1',
    icon: '🏢',
    ownerId: '1',
    memberIds: ['1', '2', '3', '4'],
    createdAt: new Date(2024, 0, 1).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ws-2',
    name: 'Marketing Team',
    description: 'Marketing campaigns and creative projects',
    color: '#ec4899',
    icon: '📱',
    ownerId: '1',
    memberIds: ['1', '3'],
    createdAt: new Date(2024, 0, 15).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

const generateMockProjects = (): Project[] => [
  {
    id: 'proj-1',
    name: 'Q1 Property Listings',
    description: 'Manage all new property listings for Q1 2025',
    workspaceId: 'ws-1',
    ownerId: '1',
    teamIds: ['1', '2'],
    status: 'active',
    color: '#3b82f6',
    icon: '🏠',
    privacy: 'public',
    dueDate: new Date(2025, 2, 31).toISOString(),
    startDate: new Date(2025, 0, 1).toISOString(),
    sections: [
      { id: 'sec-1', name: 'To Do', projectId: 'proj-1', position: 0, collapsed: false, taskIds: ['task-1', 'task-2'] },
      { id: 'sec-2', name: 'In Progress', projectId: 'proj-1', position: 1, collapsed: false, taskIds: ['task-3'] },
      { id: 'sec-3', name: 'Done', projectId: 'proj-1', position: 2, collapsed: false, taskIds: [] },
    ],
    taskIds: ['task-1', 'task-2', 'task-3'],
    customFields: [
      { id: 'cf-1', name: 'Property Type', type: 'dropdown', required: true, options: ['Apartment', 'House', 'Commercial', 'Land'] },
      { id: 'cf-2', name: 'Price Range', type: 'text', required: false },
    ],
    tags: ['real-estate', 'Q1-2025'],
    defaultView: 'board',
    createdAt: new Date(2024, 11, 1).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-2',
    name: 'Website Redesign',
    description: 'Complete overhaul of company website',
    workspaceId: 'ws-1',
    ownerId: '3',
    teamIds: ['1', '3', '4'],
    status: 'active',
    color: '#8b5cf6',
    icon: '🎨',
    privacy: 'public',
    dueDate: new Date(2025, 1, 28).toISOString(),
    startDate: new Date(2024, 11, 15).toISOString(),
    sections: [
      { id: 'sec-4', name: 'Backlog', projectId: 'proj-2', position: 0, collapsed: false, taskIds: ['task-4'] },
      { id: 'sec-5', name: 'Design', projectId: 'proj-2', position: 1, collapsed: false, taskIds: ['task-5'] },
      { id: 'sec-6', name: 'Development', projectId: 'proj-2', position: 2, collapsed: false, taskIds: [] },
      { id: 'sec-7', name: 'Testing', projectId: 'proj-2', position: 3, collapsed: false, taskIds: [] },
    ],
    taskIds: ['task-4', 'task-5'],
    customFields: [],
    tags: ['website', 'design'],
    defaultView: 'timeline',
    createdAt: new Date(2024, 11, 15).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-3',
    name: 'Social Media Campaign',
    description: 'January 2025 social media push',
    workspaceId: 'ws-2',
    ownerId: '3',
    teamIds: ['1', '3'],
    status: 'planning',
    color: '#ec4899',
    icon: '📱',
    privacy: 'public',
    dueDate: new Date(2025, 0, 31).toISOString(),
    sections: [
      { id: 'sec-8', name: 'Content Ideas', projectId: 'proj-3', position: 0, collapsed: false, taskIds: [] },
      { id: 'sec-9', name: 'In Creation', projectId: 'proj-3', position: 1, collapsed: false, taskIds: [] },
      { id: 'sec-10', name: 'Ready to Post', projectId: 'proj-3', position: 2, collapsed: false, taskIds: [] },
    ],
    taskIds: [],
    customFields: [],
    tags: ['marketing', 'social'],
    defaultView: 'calendar',
    createdAt: new Date(2024, 11, 20).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

const generateMockTasks = (): Task[] => [
  {
    id: 'task-1',
    title: 'Review new luxury apartment listings',
    description: 'Go through the 5 new luxury listings and ensure all details are correct',
    projectId: 'proj-1',
    sectionId: 'sec-1',
    assigneeId: '2',
    creatorId: '1',
    status: 'todo',
    priority: 'high',
    dueDate: new Date(2025, 0, 10).toISOString(),
    tags: ['review', 'luxury'],
    dependsOn: [],
    blockedBy: [],
    subtasks: [],
    collaboratorIds: ['1'],
    followerIds: ['3'],
    customFields: [
      { id: 'cf-1', name: 'Property Type', type: 'dropdown', required: true, value: 'Apartment' },
    ],
    attachments: [],
    comments: [],
    position: 0,
    createdAt: new Date(2025, 0, 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    title: 'Schedule property photography',
    description: 'Book professional photographer for 3 new properties',
    projectId: 'proj-1',
    sectionId: 'sec-1',
    assigneeId: '1',
    creatorId: '1',
    status: 'todo',
    priority: 'medium',
    dueDate: new Date(2025, 0, 12).toISOString(),
    tags: ['photography'],
    dependsOn: [],
    blockedBy: [],
    subtasks: [],
    collaboratorIds: [],
    followerIds: ['2'],
    customFields: [],
    attachments: [],
    comments: [],
    position: 1,
    createdAt: new Date(2025, 0, 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-3',
    title: 'Update property descriptions',
    description: 'Enhance descriptions with better SEO keywords',
    projectId: 'proj-1',
    sectionId: 'sec-2',
    assigneeId: '3',
    creatorId: '1',
    status: 'in-progress',
    priority: 'medium',
    dueDate: new Date(2025, 0, 15).toISOString(),
    startDate: new Date(2025, 0, 5).toISOString(),
    tags: ['seo', 'content'],
    dependsOn: [],
    blockedBy: [],
    subtasks: [],
    collaboratorIds: ['1', '2'],
    followerIds: [],
    customFields: [],
    attachments: [],
    comments: [
      {
        id: 'comment-1',
        text: 'Started with the downtown properties first',
        authorId: '3',
        mentions: [],
        createdAt: new Date(2025, 0, 5).toISOString(),
        updatedAt: new Date(2025, 0, 5).toISOString(),
        attachments: [],
      },
    ],
    position: 0,
    createdAt: new Date(2025, 0, 3).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-4',
    title: 'Create wireframes',
    description: 'Design initial wireframes for all major pages',
    projectId: 'proj-2',
    sectionId: 'sec-4',
    assigneeId: '3',
    creatorId: '3',
    status: 'todo',
    priority: 'high',
    dueDate: new Date(2025, 0, 8).toISOString(),
    tags: ['design', 'wireframes'],
    dependsOn: [],
    blockedBy: [],
    subtasks: [],
    collaboratorIds: [],
    followerIds: ['1', '4'],
    customFields: [],
    attachments: [],
    comments: [],
    position: 0,
    createdAt: new Date(2024, 11, 16).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-5',
    title: 'Design system components',
    description: 'Build reusable component library',
    projectId: 'proj-2',
    sectionId: 'sec-5',
    assigneeId: '3',
    creatorId: '3',
    status: 'in-progress',
    priority: 'high',
    dueDate: new Date(2025, 0, 20).toISOString(),
    startDate: new Date(2025, 0, 1).toISOString(),
    tags: ['design', 'components'],
    dependsOn: ['task-4'],
    blockedBy: [],
    subtasks: [],
    collaboratorIds: ['4'],
    followerIds: ['1'],
    customFields: [],
    attachments: [],
    comments: [],
    position: 0,
    createdAt: new Date(2024, 11, 20).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

const generateMockGoals = (): Goal[] => [
  {
    id: 'goal-1',
    title: 'Increase Property Listings by 30%',
    description: 'Expand our portfolio with quality listings',
    workspaceId: 'ws-1',
    ownerId: '1',
    status: 'on-track',
    progress: 45,
    dueDate: new Date(2025, 2, 31).toISOString(),
    startDate: new Date(2025, 0, 1).toISOString(),
    linkedProjectIds: ['proj-1'],
    linkedTaskIds: ['task-1', 'task-2'],
    keyResults: [
      { id: 'kr-1', title: 'Add 50 new listings', type: 'number', startValue: 0, targetValue: 50, currentValue: 22, unit: 'listings' },
      { id: 'kr-2', title: 'Maintain 95% quality score', type: 'percentage', startValue: 92, targetValue: 95, currentValue: 94, unit: '%' },
    ],
    createdAt: new Date(2024, 11, 1).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'goal-2',
    title: 'Complete Website Modernization',
    description: 'Launch new responsive website with improved UX',
    workspaceId: 'ws-1',
    ownerId: '3',
    status: 'on-track',
    progress: 35,
    dueDate: new Date(2025, 1, 28).toISOString(),
    startDate: new Date(2024, 11, 15).toISOString(),
    linkedProjectIds: ['proj-2'],
    linkedTaskIds: ['task-4', 'task-5'],
    keyResults: [
      { id: 'kr-3', title: 'Complete design phase', type: 'percentage', startValue: 0, targetValue: 100, currentValue: 60, unit: '%' },
      { id: 'kr-4', title: 'Reduce page load time', type: 'number', startValue: 3.5, targetValue: 1.5, currentValue: 2.8, unit: 'seconds' },
    ],
    createdAt: new Date(2024, 11, 15).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

const generateMockPortfolios = (): Portfolio[] => [
  {
    id: 'port-1',
    name: 'Q1 2025 Initiatives',
    description: 'All major projects for Q1',
    workspaceId: 'ws-1',
    ownerId: '1',
    projectIds: ['proj-1', 'proj-2'],
    color: '#6366f1',
    createdAt: new Date(2024, 11, 1).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// Export initial mock data
export const initialBalletData: BalletState = {
  workspaces: generateMockWorkspaces(),
  projects: generateMockProjects(),
  tasks: generateMockTasks(),
  goals: generateMockGoals(),
  portfolios: generateMockPortfolios(),
  users: generateMockUsers(),
  automationRules: [],
  notifications: [],
  activityEvents: [],
  forms: [],
  currentWorkspaceId: 'ws-1',
  currentProjectId: 'proj-1',
  currentView: 'board',
}

// Helper functions
export const getUserById = (users: User[], userId: string): User | undefined => {
  return users.find((u) => u.id === userId)
}

export const getProjectById = (projects: Project[], projectId: string): Project | undefined => {
  return projects.find((p) => p.id === projectId)
}

export const getTaskById = (tasks: Task[], taskId: string): Task | undefined => {
  return tasks.find((t) => t.id === taskId)
}
